fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: Infinito\Entity\User
    from_email:
        address: "%env(MAILER_SENDER)%"
        sender_name: "%env(MAILER_USER)%"
    service:
        mailer: fos_user.mailer.twig_swift
