twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        layer_action_map: "@Infinito\\Domain\\LayerManagement\\LayerActionMap"
        requested_action_service: "@Infinito\\Domain\\RequestManagement\\Action\\RequestedActionService"
        action_icon_class_map: "@Infinito\\Domain\\TwigManagement\\ActionIconClassMap"
        layer_icon_class_map: "@Infinito\\Domain\\TwigManagement\\LayerIconClassMap"
        action_template_name_service: "@Infinito\\Domain\\TemplateManagement\\ActionTemplateNameServiceInterface"
        # @todo rename variable
        action_template_data_store_service: "@Infinito\\Domain\\DataAccessManagement\\ActionsViewsDAOService"
        # @todo Remove dom service
        entity_dom_service: "@Infinito\\Domain\\DomManagement\\EntityDomServiceInterface"