language: php
php:
    - 7.2
git:
    submodules: false
services:
    - mysql
before_install:
    - mysql -e 'CREATE DATABASE DEV_DATABASE;'
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
    - cd application/symfony
    - cp phpunit.xml.dist phpunit.xml
    - cp .env.dist .env
    - sed -i 's/DEV_USER:userpass@db/travis@127.0.0.1/g' phpunit.xml
    - sed -i 's/DEV_USER:userpass@db/travis@127.0.0.1/g' .env
before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev
    - bin/console doctrine:schema:update --force
    - php bin/console doctrine:fixtures:load -n
script:
    - php ./vendor/bin/php-cs-fixer fix -v --diff --dry-run ./src/
    - bin/console doctrine:schema:validate --skip-sync
    - vendor/bin/phpunit --coverage-clover=coverage.xml
    - shellcheck administration/*.sh
after_success:
    - bash <(curl -s https://codecov.io/bash)
