language: php
php:
    - 7.2
git:
    submodules: false
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
    - cd application
    - cp phpunit.xml.dist phpunit.xml
before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev
script:
    - bin/console doctrine:schema:validate --skip-sync
    - vendor/bin/phpunit --coverage-clover=coverage.xml
after_success:
    - bash <(curl -s https://codecov.io/bash)
