sudo: required
language: php
php:
    - 7.2
git:
    submodules: false
services:
    - docker
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
before_script:
    - travis_retry bash administration/init.sh
script:
    - bash administration/test-everything.sh
after_success:
    - cd docker-symfony
    - docker-compose exec php vendor/bin/phpunit --coverage-clover=coverage.xml
    - docker-compose exec php bash <(curl -s https://codecov.io/bash)
