language: php
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - hhvm
git:
    submodules: false
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
    - cd application
before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev
script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml
after_success:
    - bash <(curl -s https://codecov.io/bash)
